### ISSUE TITLE
Suggestion for improving code reference

### ISSUE THREAD

**Issue by heytitle** [mrpeerat/SEFR_CUT#3]
For this line: https://github.com/mrpeerat/SEFR_CUT/blob/master/sefr_cut/SEFR_CUT.py#L154

It's good that you acknowledge the source; however, imho, it would be better to provide the URL to the file. So, one can easily track down the source if needed.

Also, the fact that the comment uses a nickname might be difficult to general audience to grasp whose nickname is.

**Comment by mrpeerat** [comment]
Thank you so much for the suggestion lets me fix that

**Comment by mrpeerat** [comment]
Fixed
