### ISSUE TITLE
Skipping certain characters

### ISSUE THREAD

**Issue by Bancherd-DeLong** [mrpeerat/SEFR_CUT#5]
Is there a way to skep certain sequence of characters during segmentation?  For example, I would like to have the sequence "aBcDeF" intact.

Tx,
บรรเจิด

**Comment by mrpeerat** [comment]
Hi
Can you try this
```python
import sefr_cut
sefr_cut.load_model(engine='ws1000')
print(sefr_cut.tokenize('aBcDeF'))
```

And Send me the result.
For me, the result is
```python
[['aBcDeF']]
```
Everything looks normal

**Comment by mrpeerat** [comment]
I think we talked on Facebook right?
If not you can re-open it
